# Generated by Django 6.0.2 on 2026-03-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sous_traitants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustraitant',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='soustraitant',
            name='code_postal',
            field=models.CharField(blank=True, max_length=5, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='soustraitant',
            name='siret',
            field=models.CharField(blank=True, max_length=14, verbose_name='SIRET'),
        ),
        migrations.AddField(
            model_name='soustraitant',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='soustraitant',
            name='nom',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom / Raison sociale'),
        ),
        migrations.AddConstraint(
            model_name='soustraitant',
            constraint=models.UniqueConstraint(condition=models.Q(('siret', ''), _negated=True), fields=('siret',), name='unique_siret_non_vide'),
        ),
    ]
