# Generated by Django 6.0.2 on 2026-02-27 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.bdc.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sous_traitants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bailleur",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=150, unique=True, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(
                        help_text="Code court utilisé dans l'application. Ex: GDH, ERILIA",
                        max_length=20,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bailleur",
                "verbose_name_plural": "Bailleurs",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="BonDeCommande",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_bdc", models.CharField(max_length=50, unique=True, verbose_name="N° BDC")),
                ("numero_marche", models.CharField(blank=True, max_length=100, verbose_name="N° Marché")),
                ("date_emission", models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                (
                    "programme_residence",
                    models.CharField(blank=True, max_length=200, verbose_name="Programme / Résidence"),
                ),
                ("adresse", models.CharField(max_length=255, verbose_name="Adresse")),
                ("code_postal", models.CharField(blank=True, max_length=10, verbose_name="Code postal")),
                ("ville", models.CharField(blank=True, max_length=100, verbose_name="Ville")),
                ("logement_numero", models.CharField(blank=True, max_length=50, verbose_name="N° Logement")),
                ("logement_type", models.CharField(blank=True, max_length=20, verbose_name="Type logement")),
                ("logement_etage", models.CharField(blank=True, max_length=20, verbose_name="Étage")),
                ("logement_porte", models.CharField(blank=True, max_length=20, verbose_name="Porte")),
                ("objet_travaux", models.TextField(blank=True, verbose_name="Objet / Nature des travaux")),
                ("delai_execution", models.DateField(blank=True, null=True, verbose_name="Délai d'exécution")),
                ("occupant_nom", models.CharField(blank=True, max_length=150, verbose_name="Nom occupant")),
                ("occupant_telephone", models.CharField(blank=True, max_length=20, verbose_name="Tél. occupant")),
                ("occupant_email", models.EmailField(blank=True, max_length=254, verbose_name="Email occupant")),
                ("emetteur_nom", models.CharField(blank=True, max_length=150, verbose_name="Émetteur bailleur")),
                ("emetteur_telephone", models.CharField(blank=True, max_length=20, verbose_name="Tél. émetteur")),
                (
                    "montant_ht",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Montant HT (€)"
                    ),
                ),
                (
                    "montant_tva",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="TVA (€)"
                    ),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Montant TTC (€)"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[("VACANT", "Vacant"), ("OCCUPE", "Occupé")],
                        help_text="Obligatoire avant passage en statut 'À faire'",
                        max_length=10,
                        verbose_name="Vacant / Occupé",
                    ),
                ),
                (
                    "modalite_acces",
                    models.TextField(
                        blank=True, help_text="Clés, passes, gardien, agence...", verbose_name="Modalité d'accès"
                    ),
                ),
                ("rdv_pris", models.BooleanField(default=False, verbose_name="RDV pris")),
                ("rdv_date", models.DateTimeField(blank=True, null=True, verbose_name="Date / heure du RDV")),
                ("notes", models.TextField(blank=True, verbose_name="Notes libres")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A_TRAITER", "À traiter"),
                            ("A_FAIRE", "À faire"),
                            ("EN_COURS", "En cours"),
                            ("A_FACTURER", "À facturer"),
                            ("FACTURE", "Facturé"),
                        ],
                        default="A_TRAITER",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "montant_st",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Montant attribué au sous-traitant",
                        max_digits=10,
                        null=True,
                        verbose_name="Montant ST (€)",
                    ),
                ),
                (
                    "pourcentage_st",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pourcentage du BDC attribué au sous-traitant",
                        max_digits=5,
                        null=True,
                        verbose_name="% ST",
                    ),
                ),
                (
                    "pdf_original",
                    models.FileField(
                        blank=True,
                        help_text="Fichier PDF du BDC tel que reçu du bailleur",
                        upload_to=apps.bdc.models.pdf_upload_path,
                        verbose_name="PDF original",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Modifié le")),
                (
                    "bailleur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bons_de_commande",
                        to="bdc.bailleur",
                        verbose_name="Bailleur",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bons_de_commande_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "sous_traitant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_de_commande",
                        to="sous_traitants.soustraitant",
                        verbose_name="Sous-traitant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de commande",
                "verbose_name_plural": "Bons de commande",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création"),
                            ("MODIFICATION", "Modification"),
                            ("STATUT_CHANGE", "Changement de statut"),
                            ("ATTRIBUTION", "Attribution"),
                            ("REATTRIBUTION", "Réattribution"),
                            ("NOTIFICATION_SMS", "SMS envoyé"),
                            ("VALIDATION", "Validation réalisation"),
                            ("FACTURATION", "Passage en facturation"),
                        ],
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="Informations complémentaires en JSON (ex: ancien/nouveau statut)",
                        null=True,
                        verbose_name="Détails",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Date / heure")),
                (
                    "bdc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="bdc.bondecommande",
                        verbose_name="BDC",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions_bdc",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action historisée",
                "verbose_name_plural": "Historique des actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LignePrestation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("designation", models.TextField(verbose_name="Désignation")),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Quantité")),
                ("unite", models.CharField(blank=True, max_length=20, verbose_name="Unité")),
                (
                    "prix_unitaire",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix unitaire (€)"),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant (€)")),
                ("ordre", models.PositiveSmallIntegerField(default=0, verbose_name="Ordre")),
                (
                    "bdc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_prestation",
                        to="bdc.bondecommande",
                        verbose_name="BDC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de prestation",
                "verbose_name_plural": "Lignes de prestation",
                "ordering": ["ordre"],
            },
        ),
    ]
