# Generated by Django 6.0.2 on 2026-02-28 07:31

from django.db import migrations, models


def _pdf_terrain_upload_path(instance, filename):
    """Historical upload path for pdf_terrain (field removed in 0008)."""
    import os
    from datetime import date
    today = date.today()
    return f"bdc_terrain/{today.year}/{today.month:02d}/{instance.numero_bdc}_terrain.pdf"


class Migration(migrations.Migration):
    dependencies = [
        ("bdc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondecommande",
            name="pdf_terrain",
            field=models.FileField(
                blank=True,
                help_text="Version sans prix du BDC, destinée au sous-traitant",
                upload_to=_pdf_terrain_upload_path,
                verbose_name="PDF terrain",
            ),
        ),
    ]
