# Generated by Django 6.0.2 on 2026-02-28 07:31

from django.db import migrations, models

import apps.bdc.models


class Migration(migrations.Migration):
    dependencies = [
        ("bdc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondecommande",
            name="pdf_terrain",
            field=models.FileField(
                blank=True,
                help_text="Version sans prix du BDC, destinée au sous-traitant",
                upload_to=apps.bdc.models.pdf_terrain_upload_path,
                verbose_name="PDF terrain",
            ),
        ),
    ]
