# Generated by Django 6.0.2 on 2026-02-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdc", "0002_add_pdf_terrain"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondecommande",
            name="date_realisation",
            field=models.DateField(
                blank=True,
                help_text="Date à laquelle les travaux ont été déclarés terminés",
                null=True,
                verbose_name="Date de réalisation",
            ),
        ),
    ]
