# Generated by Django 6.0.2 on 2026-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdc", "0008_remove_bondecommande_pdf_terrain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bailleur",
            name="marqueur_detection",
            field=models.CharField(
                blank=True,
                help_text="Texte unique dans les PDF de ce bailleur (ex: 'ICF HABITAT')",
                max_length=100,
                verbose_name="Marqueur de détection PDF",
            ),
        ),
        migrations.AddField(
            model_name="bailleur",
            name="modele_extraction",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mapping champ → label pour extraction automatique",
                verbose_name="Modèle d'extraction PDF",
            ),
        ),
        migrations.AddField(
            model_name="bailleur",
            name="pdf_modele",
            field=models.FileField(blank=True, upload_to="bailleurs/modeles/", verbose_name="PDF modèle"),
        ),
    ]
