# Generated by Django 6.0.2 on 2026-03-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdc", "0009_bailleur_extraction_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checklistitem",
            options={
                "ordering": ["transition", "ordre"],
                "verbose_name": "Item de checklist",
                "verbose_name_plural": "Items de checklist",
            },
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="transition",
            field=models.CharField(
                choices=[
                    ("A_TRAITER__A_FAIRE", "Contrôle → À attribuer"),
                    ("A_FAIRE__EN_COURS", "Attribution → En cours"),
                    ("EN_COURS__A_FACTURER", "Réalisation → À facturer"),
                    ("A_FACTURER__FACTURE", "Facturation → Facturé"),
                ],
                default="A_TRAITER__A_FAIRE",
                max_length=30,
            ),
        ),
    ]
