# Generated by Django 6.0.2 on 2026-03-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdc", "0010_checklistitem_transition"),
    ]

    operations = [
        migrations.AddField(
            model_name="bailleur",
            name="pages_a_envoyer",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des numéros de page à inclure (ex: [1]). Vide = toutes les pages.",
                verbose_name="Pages PDF à envoyer au ST",
            ),
        ),
    ]
