# Generated by Django 6.0.2 on 2026-03-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdc", "0011_bailleur_pages_a_envoyer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bailleur",
            name="champs_masques",
        ),
        migrations.AddField(
            model_name="bailleur",
            name="zones_masquage",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Rectangles de masquage [{x, y, w, h, page, label}]. Coordonnées en points PDF.",
                verbose_name="Zones à masquer sur le PDF",
            ),
        ),
    ]
