# Generated by Django 6.0.2 on 2026-03-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdc", "0013_config_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrixForfaitaire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(max_length=50, unique=True, verbose_name="Référence")),
                ("designation", models.CharField(max_length=200, verbose_name="Désignation")),
                ("unite", models.CharField(help_text="u, m², ml, forfait…", max_length=20, verbose_name="Unité")),
                (
                    "prix_unitaire",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix unitaire (€)"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Prix forfaitaire",
                "verbose_name_plural": "Prix forfaitaires",
                "ordering": ["reference"],
            },
        ),
        migrations.AddField(
            model_name="bondecommande",
            name="mode_attribution",
            field=models.CharField(
                blank=True,
                choices=[("pourcentage", "Pourcentage"), ("forfait", "Forfait")],
                max_length=15,
                verbose_name="Mode d'attribution",
            ),
        ),
        migrations.CreateModel(
            name="LigneForfaitAttribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Quantité")),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pré-rempli depuis la bibliothèque, modifiable",
                        max_digits=10,
                        verbose_name="Prix unitaire (€)",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant (€)")),
                (
                    "bdc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_forfait",
                        to="bdc.bondecommande",
                        verbose_name="BDC",
                    ),
                ),
                (
                    "prix_forfaitaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bdc.prixforfaitaire",
                        verbose_name="Prix forfaitaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne forfait attribution",
                "verbose_name_plural": "Lignes forfait attribution",
            },
        ),
    ]
