# Generated by Django 6.0.2 on 2026-08-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdc", "0017_type_bon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondecommande",
            name="type_acces",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BADGE_CODE", "Badge / Code"),
                    ("CLE", "Clé à récupérer"),
                    ("PASS_CHANTIER", "Pass chantier"),
                ],
                max_length=15,
                verbose_name="Type d'accès",
            ),
        ),
        migrations.AlterField(
            model_name="configemail",
            name="corps",
            field=models.TextField(
                blank=True,
                help_text="Variables : {numero_bdc}, {adresse}, {ville}, {travaux}, {delai}, {etage}, {porte}, {commentaire}",
                verbose_name="Corps du mail",
            ),
        ),
        migrations.AlterField(
            model_name="configemail",
            name="sujet",
            field=models.CharField(
                blank=True,
                help_text="Variables : {numero_bdc}, {adresse}, {ville}, {travaux}, {delai}, {etage}, {porte}",
                max_length=200,
                verbose_name="Sujet du mail",
            ),
        ),
        migrations.AlterField(
            model_name="historiqueaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATION", "Création"),
                    ("MODIFICATION", "Modification"),
                    ("STATUT_CHANGE", "Changement de statut"),
                    ("ATTRIBUTION", "Attribution"),
                    ("REATTRIBUTION", "Réattribution"),
                    ("ANNULATION", "Annulation d'attribution"),
                    ("NOTIFICATION_SMS", "SMS envoyé"),
                    ("VALIDATION", "Validation réalisation"),
                    ("FACTURATION", "Passage en facturation"),
                    ("RENVOI", "Renvoi au contrôle"),
                ],
                max_length=30,
                verbose_name="Action",
            ),
        ),
    ]
