# Generated by Django 6.0.2 on 2026-10-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdc", "0018_alter_bondecommande_type_acces_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondecommande",
            name="date_facturation",
            field=models.DateField(
                blank=True,
                help_text="Saisie au passage 'À facturer' → 'Facturé'",
                null=True,
                verbose_name="Date de facturation",
            ),
        ),
        migrations.AddField(
            model_name="bondecommande",
            name="date_intervention",
            field=models.DateField(
                blank=True,
                help_text="Date réelle de l'intervention, saisie au passage 'En cours' → 'À facturer'",
                null=True,
                verbose_name="Date d'intervention",
            ),
        ),
        migrations.AddField(
            model_name="bondecommande",
            name="numero_facture",
            field=models.CharField(
                blank=True,
                help_text="Saisi au passage 'À facturer' → 'Facturé'",
                max_length=50,
                verbose_name="N° de facture",
            ),
        ),
    ]
