# Generated by Django 6.0.2 on 2026-10-05 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bdc", "0018_alter_bondecommande_type_acces_and_more"),
        ("sous_traitants", "0002_soustraitant_adresse_soustraitant_code_postal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bondecommande",
            name="date_facturation",
            field=models.DateField(blank=True, null=True, verbose_name="Date de facturation"),
        ),
        migrations.AddField(
            model_name="bondecommande",
            name="numero_facture",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Saisi au passage en 'Facturé'",
                max_length=50,
                verbose_name="N° de facture",
            ),
        ),
        migrations.AlterField(
            model_name="bondecommande",
            name="date_realisation",
            field=models.DateField(
                blank=True,
                help_text="Date à laquelle les travaux ont été réalisés, saisie au passage en 'À facturer'",
                null=True,
                verbose_name="Date d'intervention",
            ),
        ),
        migrations.AddConstraint(
            model_name="bondecommande",
            constraint=models.UniqueConstraint(
                condition=models.Q(("numero_facture", ""), _negated=True),
                fields=("numero_facture",),
                name="bdc_numero_facture_unique",
            ),
        ),
    ]
