# Generated by Django 6.0.2 on 2026-08-15 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.changelog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, validators=[apps.changelog.models.valider_numero_calver])),
                ('date_mise_en_ligne', models.DateField()),
                ('resume', models.TextField()),
                ('changements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'ordering': ['-date_mise_en_ligne', '-created_at'],
            },
        ),
    ]
